"""initial migration

Revision ID: 488e4c32347b
Revises: None
Create Date: 2016-06-13 00:34:34.853636

"""

# revision identifiers, used by Alembic.
revision = '488e4c32347b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('random_key', sa.String(length=120), nullable=True),
    sa.Column('url', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('random_key')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Url')
    ### end Alembic commands ###
